### PR TITLE
feat: analytics custom events

### PR DESCRIPTION
**Pull request by andrewlew1s**
This is to aid #23

### CODE REVIEW

**Comment by andrewlew1s** [comment]
I have discovered the method to see custom events logged in real time. 

- Go to Firebase Analytics
- Go to Debug View section (the last option under analytics menu)
- Install [Analytics Debugger](https://chrome.google.com/webstore/detail/google-analytics-debugger/jnkmfdileelhofjcijamephohjechhna) Chrome Extension
- Spin up localhost of tool / site you are adding custom events to
- Run the newly installed chrome extension by clicking on the extension in the chrome taskbar itself
- Now you can fire your event and see it in the debug view console

**Comment by andrewlew1s** [comment]
We still need to test a custom event on a deployed site. This should be simple and just deploy a site with a new event. 
We should also compile a list of events we want to track, and implement them.

**Comment by michaelfitzhavey** [comment]
According to the comments in this PR this seems to be hard coding individual events into the codebase, from what I know about Google tag manager we don't need to do this, perhaps I am wrong?

**Comment by andrewlew1s** [comment]
We are not going to merge this branch as we are now using google tag manager in order to do add events in a console without changing the code. This is in #62

**Pull request closed without merging**
